aws_profile                = "KEVIN-ZYL"
project                    = "zyl-elevator"
environment                = "dev"
region                     = "ap-southeast-1"
sub_tag                    = "Yoma Elevator"
vpc_cidr                   = "10.61.0.0/16"
azs                        = ["ap-southeast-1a", "ap-southeast-1b", "ap-southeast-1c"]
public_subnet_cidrs        = ["10.61.1.0/24", "10.61.2.0/24", "10.61.3.0/24"]
private_subnet_cidrs       = ["10.61.4.0/24", "10.61.5.0/24", "10.61.6.0/24"]
db_subnet_cidrs            = ["10.61.7.0/24", "10.61.8.0/24", "10.61.9.0/24"]
be_image                   = "REPLACE_WITH_BE_IMAGE_URI:tag"
fe_image                   = "REPLACE_WITH_FE_IMAGE_URI:tag"
be_port                    = 3001
fe_port                    = 3000
alb_certificate_arn        = "REPLACE_ap-southeast-1_ACM_ARN"
cloudfront_certificate_arn = "REPLACE_us-east-1_ACM_ARN"
cloudfront_aliases         = []
waf_allowed_countries      = []
be_secrets                 = {}
fe_secrets                 = {}
